export const Constants = {
    densityOfSteel: 490, //Ib/ft3
    TOKEN_KEY: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDRFqNtPG6tkj5ytCPIJBiwuT1HEHQYqmUSSHyekElclwfdqRqTtDCx4cF/IxyQZvIh21GRcM8DFhSMSobDiDD7gbAZVxIgsXztGuyy+xb/DnDKtYiktScWL20rLThILTHWk9VbUjhJGU3Krfz4fsUeFXQJLfQpydU63ABGODcKowIDAQAB",
}